### ISSUE TITLE
loading jQuery can make JS work which don't without the toolbar

### ISSUE THREAD

**Issue by Schrank** [mgtcommerce/Mgt_Developertoolbar#10]
We have jQuery in our project Version 1.8.3 with `noConflict()`. And I implemented some JS code, which ran perfect on my local system, but not on live.

After clearing the jQuery file from the toolbar, the code didn't work locally either.

I recommend (yes, it is a lot of work) to reimplement the JS in prototype.

Maybe I'll do this, but at the moment this project seems to be abandoned and the PRs are not processed :(

**Comment by millejano** [comment]
Maybe you can use my fork, where you can disable the jquery support.

https://github.com/millejano/Wee_Developertoolbar/blob/master/htdocs/app/code/community/Wee/DeveloperToolbar/etc/system.xml
