### ISSUE TITLE
install the module without adding a specific repo

### ISSUE THREAD

**Issue by spipu** [mgtcommerce/Mgt_Developertoolbar#18]
Hi !

your toolbar is really great.

Could you add it to https://packagist.org/ ? because adding a specific repo in the composer.json file is not a good practice.

additionally, the given command to add the repo is not good because it transforms the repo node of the composer.json file from array to object.

Thanks !

Laurent

**Comment by swieczorek** [comment]
Hi Laurent,
thanks for your feedback.

I have added the toolbar to https://packagist.org/ and updated the installation guide.

Thanks,
Stefan
