### ISSUE TITLE
Duplicate Router ID

### ISSUE THREAD

**Issue by DavidLambauer** [mgtcommerce/Mgt_Developertoolbar#22]
## Steps to reproduce
1. Install the Toolbar
2. Try to merge the Xml
## Expected result
1. Shop should appear
## Actual result
1. The router.xml contains two routers with the same ID. This will throw an Error.
   Invalid XML in file src/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/etc/frontend/routes.xml: Element 'config': Missing child element(s). Expected is ( router ). Line: 2

I am using Magento 2.1.1

**Comment by taitdigital** [comment]
Have a similar issue 
1 exception(s):

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /Applications/MAMP/htdocs/magedemo/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/etc/frontend/routes.xml:
Element 'router': Duplicate key-sequence ['standard'] in unique identity-constraint 'uniqueRouterId'.
Line: 8

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /Applications/MAMP/htdocs/magedemo/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/etc/frontend/routes.xml:
Element 'router': Duplicate key-sequence ['standard'] in unique identity-constraint 'uniqueRouterId'.
Line: 8

**Comment by swieczorek** [comment]
Thanks for reporting the issue. It's now fixed in version 1.0.1
