### ISSUE TITLE
Handle "mgt_developer_toolbar_view" not loading

### ISSUE THREAD

**Issue by Vedrillan** [mgtcommerce/Mgt_Developertoolbar#24]
On the dashboard or any section of the toolbar I am having the following error:

> Fatal error: Call to a member function setCurrentUrl() on boolean in /var/www/project/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/Helper/Toolbar.php on line 172

It looks like the layout file mgt_developer_toolbar_view.xml is not loaded, hence the block mgt_developer_toolbar_container not being returned.

Current setup is on Magento EE 2.1.2 and "mgtcommerce/module-mgtdevelopertoolbar dev-master f3867c4"

**Comment by swieczorek** [comment]
It
