### ISSUE TITLE
Consider namespacing '.container' or all classnames

### ISSUE THREAD

**Issue by garypburton** [mgtcommerce/Mgt_Developertoolbar#28]
The .container class in your stylesheet was overriding styles in a site I was working on - I didn't realise this as not familiar with said site so wasted a fair bit of time trying to debug it. It must be a fairly widely used class name so I would have thought this could be a fairly common issue.

**Comment by gabealeman** [comment]
Agreed, this just creates frontend inconsistencies when the toolbar is enabled.

**Comment by Xoce51** [comment]
Hi @swieczorek antyhing planned about this issue ?
Why are you using `.container` selector and not more specific selector ?
