### ISSUE TITLE
Install with Composer: add --dev flag

### ISSUE THREAD

**Issue by VincentMarmiesse** [mgtcommerce/Mgt_Developertoolbar#36]
Hello,

When installing the module with Composer, I think you should add the `--dev` flag so the module is installed into the `require-dev` section and not installed if you run `composer install --no-dev`.

The installation command becomes 
```
composer require --dev mgtcommerce/module-mgtdevelopertoolbar
```

**Comment by swieczorek** [comment]
Thanks, we have updated our documentation:

https://www.mgt-commerce.com/documentation/magento2-mgt-developer-toolbar
