### ISSUE TITLE
Error in php info section for Magento 2.3 with php 7.2.x

### ISSUE THREAD

**Issue by Hanhan1989** [mgtcommerce/Mgt_Developertoolbar#37]
There is an error in `Phpinfo.php` file. 

`
 Exception #0 (Exception): Deprecated Functionality: Function create_function() is deprecated in /var/www/html/src/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/Block/Toolbar/Container/Sidebar/Block/Phpinfo.php on line 43
`

It seems that the function `create_function()` is in deprecated state for Magento 2.3 with php 7.2.x

**Comment by csOrkoh** [comment]
In the file app/code/Mgt/DeveloperToolbar/Block/Toolbar/Container/Sidebar/Block/Phpinfo.php
replace 

create_function(
                    '$i',
                    'return ".mgt-developer-toolbar-phpinfo-display " . preg_replace( "/,/", ",.phpinfodisplay ", $i );'
                ),

By

function($i){ 
	return ".mgt-developer-toolbar-phpinfo-display " . preg_replace("/,/", ",.phpinfodisplay ", $i);
},
