### ISSUE TITLE
Undefined index: instance

### ISSUE THREAD

**Issue by atty31** [mgtcommerce/Mgt_Developertoolbar#52]
Hi, I am receiving this error mesage: 
`Exception #0 (Exception): Notice: Undefined index: instance in vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/view/frontend/templates/toolbar/container/sidebar/events.phtml on line 29`
when I press the Events item from the menu. 
I am runnign magento 2.4.2-p1 and version 1.0.9 of the mgtcommerce/module-mgtdevelopertoolbar module 
Would you please have a look ? 
Thanks

**Comment by aweb3r** [comment]
same in 2.4.6

**Comment by aweb3r** [comment]
[mgt-patch-events.patch](https://github.com/mgtcommerce/Mgt_Developertoolbar/files/14064460/mgt-patch-events.patch)
