### ISSUE TITLE
Error when updating 2.4.4 and php8.1 : MGT developer toolbar issue

### ISSUE THREAD

**Issue by ghost** [mgtcommerce/Mgt_Developertoolbar#55]
Issue when upgrading Magento 2.4.4/php8.1. MGT developer toolbar issue -> 
Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/MYWEBSITE/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/Model/Config.php on line 77.

Any idea to solve this problem without overriding this file each time we upgrade Magento 2.4.4 ?

Thanks :)

**Comment by roubzy1704** [comment]
Take a look at the pull request https://github.com/mgtcommerce/Mgt_Developertoolbar/pull/54, someone posted some solutions to a couple of the problems with Magento 2.4.4/php8.1

**Comment by roubzy1704** [comment]
> Issue when upgrading Magento 2.4.4/php8.1. MGT developer toolbar issue -> Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/MYWEBSITE/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/Model/Config.php on line 77.
> 
> Any idea to solve this problem without overriding this file each time we upgrade Magento 2.4.4 ?
> 
> Thanks :)


Take a look at the pull request https://github.com/mgtcommerce/Mgt_Developertoolbar/pull/54, someone posted some solutions to a couple of the problems with Magento 2.4.4/php8.1

**Comment by petehouston** [comment]
this one is different, it is the problem of parsing the `Allowed IP` config field of this extension, by default, it is empty, which is `NULL`. 

https://github.com/mgtcommerce/Mgt_Developertoolbar/blob/master/src/app/code/Mgt/DeveloperToolbar/Model/Config.php#L77

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/9006720/209190541-07a31dfa-e5ea-4a27-a2ce-bbb30ac70f7f.png">

The latest version of this extension does not fix it. I'm not certain if there is anyone making a PR to fix, I could create one PR to fix.

For a quick fix without patching the code, go to Admin dashboard > Configuration, expand and select MGT Developer Toolbar config section, put in the `Allowed IPs` field value as `,` (a comma) to allow any IP access or your IPs for restrictions.

**Comment by swieczorek** [comment]
Has been fixed.
