### ISSUE TITLE
Developer restrictions should use the same developer restrictions as the template path hints

### ISSUE THREAD

**Issue by paales** [mgtcommerce/Mgt_Developertoolbar#7]

**Comment by paales** [comment]
This adds extra weight on configuring the backend, if the IP isn't filled in the developer toolbar is shown for everyone, while using the normal developer restrictions this part is already set up.

Again, if you guys accept pull requests I can make the changes :)

**Comment by Schrank** [comment]
maybe the settings should be moved to developer settings. then it makes sense to use the IP of the template hints.
You shouldn't split the settings.
